name: Build SDK

on:
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.event_name  }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup SDK
      run: |
        sudo apt update
        sudo apt install bash cmake wget build-essential clang clang-15 lld lld-15 python3 python3-pyelftools
        make
        make DESTDIR=${{ runner.tool_cache }}/ps5-payload-sdk install
        echo PS5_PAYLOAD_SDK=${{ runner.tool_cache }}/ps5-payload-sdk >> $GITHUB_ENV
        echo PS5_HOST=ps5 >> $GITHUB_ENV
        echo PS5_PORT=9021 >> $GITHUB_ENV
        tar -zcf ps5-payload-sdk.tar.gz -C ${{ runner.tool_cache }}/ps5-payload-sdk .

    - name: Build
      run: |
        make -C samples/ps5-payload-hbldr
        bash samples/hello_cmake/build.sh

    - name: Upload SDK
      uses: actions/upload-artifact@v3
      with:
        name: SDK
        path: ./ps5-payload-sdk.tar.gz
        if-no-files-found: error

    - name: Upload payload
      uses: actions/upload-artifact@v3
      with:
        name: Payload binaries
        path: ./**/*.elf
        if-no-files-found: error
